name: Tests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main, dev]

jobs:
  matlab-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v3

      - name: Run MATLAB Tests
        uses: matlab-actions/run-command@v3
        with:
          generate-summary: true
          command: |
            addpath(pwd)
            suite = testsuite('tests', 'IncludeSubfolders', true);
            runner = matlab.unittest.TestRunner.withDefaultPlugins;
            results = runner.run(suite);
            display(results)
            assertSuccess(results)
